language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8
  - python setup.py sdist
  - pip install dist/reachablelib-$(cat VERSION).tar.gz
